export const GET_ARTICLES_LIST_BEGIN = 'GET_ARTICLES_LIST_BEGIN'
export const GET_ARTICLES_LIST_SUCCESS = 'GET_ARTICLES_LIST_SUCCESS'
export const GET_ARTICLES_LIST_FAILURE = 'GET_ARTICLES_LIST_FAILURE'

export const CREATE_ARTICLES_CONTENT_BEGIN = 'CREATE_ARTICLES_CONTENT_BEGIN'
export const CREATE_ARTICLES_CONTENT_SUCCESS = 'CREATE_ARTICLES_CONTENT_SUCCESS'
export const CREATE_ARTICLES_CONTENT_FAILURE = 'CREATE_ARTICLES_CONTENT_FAILURE'

export const DELETE_ARTICLES_BEGIN = 'DELETE_ARTICLES_BEGIN'
export const DELETE_ARTICLES_SUCCESS = 'DELETE_ARTICLES_SUCCESS'
export const DELETE_ARTICLES_FAILURE = 'DELETE_ARTICLES_FAILURE'

export const UPDATE_ARTICLES_BEGIN = 'UPDATE_ARTICLES_BEGIN'
export const UPDATE_ARTICLES_SUCCESS = 'UPDATE_ARTICLES_SUCCESS'
export const UPDATE_ARTICLES_FAILURE = 'UPDATE_ARTICLES_FAILURE'

export const SEARCH_ARTICLES_BEGIN = 'SEARCH_ARTICLES_BEGIN'
export const SEARCH_ARTICLES_SUCCESS = 'SEARCH_ARTICLES_SUCCESS'
export const SEARCH_ARTICLES_FAILURE = 'SEARCH_ARTICLES_FAILURE'
