export const GET_TODOS_LIST_BEGIN='GET_TODOS_LIST_BEGIN'
export const GET_TODOS_LIST_SUCCESS='GET_TODOS_LIST_SUCCESS'
export const GET_TODOS_LIST_FAILURE='GET_TODOS_LIST_FAILURE'

export const COMPLETE_TODOS_BEGIN='COMPLETE_TODOS_BEGIN'
export const COMPLETE_TODOS_SUCCESS='COMPLETE_TODOS_SUCCESS'
export const COMPLETE_TODOS_FAILURE='COMPLETE_TODOS_FAILURE'

export const ADD_TODOS_BEGIN='ADD_TODOS_BEGIN'
export const ADD_TODOS_SUCCESS='ADD_TODOS_SUCCESS'
export const ADD_TODOS_FAILURE='ADD_TODOS_FAILURE'

export const DELETE_TODOS_BEGIN='DELETE_TODOS_BEGIN'
export const DELETE_TODOS_SUCCESS='DELETE_TODOS_SUCCESS'
export const DELETE_TODOS_FAILURE='DELETE_TODOS_FAILURE'

export const UPDATE_TODOS_BEGIN='UPDATE_TODOS_BEGIN'
export const UPDATE_TODOS_SUCCESS='UPDATE_TODOS_SUCCESS'
export const UPDATE_TODOS_FAILURE='UPDATE_TODOS_FAILURE'

export const FILTER_TODOS_BEGIN='FILTER_TODOS_BEGIN'
export const FILTER_TODOS_SUCCESS='FILTER_TODOS_SUCCESS'
export const FILTER_TODOS_FAILURE='FILTER_TODOS_FAILURE'

export const GET_MAIN_WEATHER = 'GET_MAIN_WEATHER'