export const GET_HOME_ARTICLE_LIST_BEGIN = 'GET_HOME_ARTICLE_LIST_BEGIN'
export const GET_HOME_ARTICLE_LIST_SUCCESS = 'GET_HOME_ARTICLE_LIST_SUCCESS'
export const GET_HOME_ARTICLE_LIST_FAILURE = 'GET_HOME_ARTICLE_LIST_FAILURE'

export const NEXT_HOME_ARTICLE_LIST = 'NEXT_HOME_ARTICLE_LIST'